version: '3.4'

services:
  parametrage:
    image: ${DOCKER_REGISTRY-}parametrage
    build:
      context: .
      dockerfile: Parametrage/Dockerfile

  db:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      SA_PASSWORD: 'Azerty*1234'
      ACCEPT_EULA: 'Y'
    ports:
      - 1401:1433

